//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MelhorPreco.DATA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_ENDERECO> TB_ENDERECO { get; set; }
        public virtual DbSet<TB_LISTA_COMPRAS> TB_LISTA_COMPRAS { get; set; }
        public virtual DbSet<TB_LOJA> TB_LOJA { get; set; }
        public virtual DbSet<TB_PRECO> TB_PRECO { get; set; }
        public virtual DbSet<TB_PREFERENCIA> TB_PREFERENCIA { get; set; }
        public virtual DbSet<TB_PRODUTO> TB_PRODUTO { get; set; }
        public virtual DbSet<TB_USUARIO> TB_USUARIO { get; set; }
        public virtual DbSet<TB_PERFIL> TB_PERFIL { get; set; }
    }
}
