//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MelhorPreco.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PREFERENCIA
    {
        public int PREFERENCIA_ID { get; set; }
        public int PREFERENCIA_USUARIO { get; set; }
        public int PREFERENCIA_LOJA { get; set; }
    
        public virtual TB_LOJA TB_LOJA { get; set; }
        public virtual TB_USUARIO TB_USUARIO { get; set; }
    }
}
