//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MelhorPreco.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PRODUTO
    {
        public TB_PRODUTO()
        {
            this.TB_LISTA_COMPRAS = new HashSet<TB_LISTA_COMPRAS>();
        }
    
        public long PRODUTO_EAN { get; set; }
        public string PRODUTO_DESCRICAO { get; set; }
        public Nullable<long> PRODUTO_IMAGEM { get; set; }
        public string PRODUTO_CATEGORIA { get; set; }
        public string PRODUTO_SUBCATEGORIA { get; set; }
    
        public virtual ICollection<TB_LISTA_COMPRAS> TB_LISTA_COMPRAS { get; set; }
        public virtual TB_PRECO TB_PRECO { get; set; }
    }
}
