//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MelhorPreco.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PRECO
    {
        public long PRECO_PRODUTO { get; set; }
        public int PRECO_LOJA { get; set; }
        public decimal PRECO_VALOR { get; set; }
        public System.DateTime PRECO_ATUALIZACAO { get; set; }
        public int PRECO_USUARIO_ATUALIZOU { get; set; }
    
        public virtual TB_LOJA TB_LOJA { get; set; }
        public virtual TB_PRODUTO TB_PRODUTO { get; set; }
        public virtual TB_USUARIO TB_USUARIO { get; set; }
    }
}
